name: Project Board Automation

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, closed, converted_to_draft]

jobs:
  automate_projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const COLUMNS = {
              BACKLOG: '17052d30',
              SPRINT_BACKLOG: '2b4b3335',
              IN_PROGRESS: 'dc54b4f8',
              IN_REVIEW: '3fdc4773',
              DONE: '98236657'
            };

            async function updateIssueStatus(issueNumber, columnId) {
              try {
                await github.rest.projects.updateCard({
                  card_id: context.payload.project_card?.id,
                  column_id: columnId,
                  position: 'top'
                });
              } catch (error) {
                console.error('Error updating issue status:', error);
              }
            }

            // 새 이슈가 생성되면 Backlog로 이동
            if (context.eventName === 'issues' && context.payload.action === 'opened') {
              await updateIssueStatus(context.payload.issue.number, COLUMNS.BACKLOG);
            }

            // PR이 생성되면 연결된 이슈를 In Review로 이동
            if (context.eventName === 'pull_request' && context.payload.action === 'opened') {
              await updateIssueStatus(context.payload.pull_request.number, COLUMNS.IN_REVIEW);
            }

            // 이슈나 PR이 닫히면 Done으로 이동
            if (context.payload.action === 'closed') {
              await updateIssueStatus(
                context.eventName === 'issues' 
                  ? context.payload.issue.number 
                  : context.payload.pull_request.number,
                COLUMNS.DONE
              );
            }
