name: Project Automation

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  issue_automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/github-script@v6
      with:
        script: |
          const COLUMN_IDS = {
            DONE: '98236657',
            SPRINT_BACKLOG: '2b4b3335',
            IN_PROGRESS: 'dc54b4f8',
            IN_REVIEW: '3fdc4773'
          };

          // 이슈가 생성될 때
          if (context.eventName === 'issues' && context.payload.action === 'opened') {
            await github.rest.projects.createCard({
              column_id: COLUMN_IDS.SPRINT_BACKLOG,
              content_id: context.payload.issue.id,
              content_type: 'Issue'
            });
          }

          // PR 관련 자동화
          if (context.eventName === 'pull_request') {
            const card_id = context.payload.project_card?.id;
            
            if (context.payload.action === 'opened') {
              // PR이 열릴 때 In Review로 이동
              await github.rest.projects.moveCard({
                card_id: card_id,
                column_id: COLUMN_IDS.IN_REVIEW,
                position: 'top'
              });
            } else if (context.payload.action === 'closed' && context.payload.pull_request.merged) {
              // PR이 머지되면 Done으로 이동
              await github.rest.projects.moveCard({
                card_id: card_id,
                column_id: COLUMN_IDS.DONE,
                position: 'top'
              });
            }
          }

  add_reviewers:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          await github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: ['choco5958', 'lim3873', 'tlswltjq']
          });
